golang/protobuf

README
The steps for installation are now in an easy to find list. With the previous formatting as prose, it was easy to miss the step to install the C++ version of the protocol buffer compilers. Now it will be easy to find out what to do to start using protocol buffers with Go.
=> Add headings to make clear how to install and get started.

protoc-gen-go/testdata/Makefile
"make install; make test" did not work out of the box on Ubuntu 16.04. Removing the bashism from protoc-gen-go/testdata/Makefile allows "make test" to run with a PASS result.
=> Allow "make test" to run with Bourne shell.

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This fixes #253 by ensuring `null` `json` values for `Timestamp` and `Duration` fields are treated as `zero` values, conforming to the [official documentation](https://developers.google.com/protocol-buffers/docs/proto3#json),
> If a value is missing in the JSON-encoded data or if its value is null, it will be interpreted as the appropriate default value when parsed into a protocol buffer. If a field has the default value in the protocol buffer, it will be omitted in the JSON-encoded data by default to save space. An implementation may provide options to emit fields with default values in the JSON-encoded output.
=> jsonpb: treat `null` JSON values for `Timestamp` and `Duration` as defaults

protoc-gen-go/grpc/grpc.go
Go 1.7 added context to the standard library.  With Go 1.8 coming soon here is a PR to switch from `golang.org/x/net/context` to `context.
=> Update to standard library context package.

protoc-gen-go/grpc/grpc.go
Reverts golang/protobuf#275
This is causing breakages for users. Will investigate more in-depth tomorrow.
=> Revert "Update to standard library context package."

README.md
The curlies in the go get argument is very unknown, I have
witnessed a few users parsing the argument to run the following
commands indiviually rather than copy/pasting the instruction:
$ go get -u github.com/golang/protobuf/protoc-gen-go
$ go get -u github.com/golang/protobuf/proto
go get the protoc-gen-go to simplify this step.
=> Simplify the installation step

protoc-gen-go/descriptor/Makefile, protoc-gen-go/plugin/Makefile
Instead of using checked out source, this now works with a binary
release.  Descriptor now has the go_package option set, so we no longer
need to move the files around.
=> protoc-gen-go: update Makefiles for protobuf 3.3.0

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This is achieved by delegating to the message if it implements `json.Marshaler` or `json.Unmarshaler`.
FWIW, this could simplify how the well-known types are handled (e.g. no need to special-case them in this package).
Both the binary and text encodings support the same concept, where a message can implement a particular interface (`proto.Marshaler`/`proto.Unmarshaler`, `encoding.TextMarshaler`/`encoding.TextUnmarshaler`) to customize serialization/de-serialization. This just extends that same concept to JSON encoding/decoding.
=> support custom JSON (de)serialization by delegating to message if it implements json.Marshaler/json.Unmarshaler

README.md, proto/lib.go
Remove statements regarding getters only generated for message and oneof in proto3.
=> Fix doc re. getters for proto3

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This should address #360 
I included support for the custom message type to marshal itself into JSON types other than object. So it's a little more flexible than the solution @cybrcodr suggested in #360.
Also fixed a potential nil-dereference panic if an Any type was unmarshaled from bad JSON that had a null type:
```json
{ "@type": null, "key": "value" }
```
=> fix marshaling of any types to JSON when contained object has custom marshaling

jsonpb/jsonpb.go, proto/encode.go, proto/text_parser.go
Found with github.com/mdempsky/unconvert.
/Users/tamird/src/go/src/github.com/golang/protobuf/jsonpb/jsonpb.go:625:32: unnecessary conversion
/Users/tamird/src/go/src/github.com/golang/protobuf/proto/encode.go:177:30: unnecessary conversion
/Users/tamird/src/go/src/github.com/golang/protobuf/proto/encode.go:181:26: unnecessary conversion
/Users/tamird/src/go/src/github.com/golang/protobuf/proto/text_parser.go:868:21: unnecessary conversion
=> Remove unncessary conversions

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Unmarshaling now follows proto3 spec, turning JSON `null` into Go `nil` for wrapper types. Without this fix, `(Type)Value` wrappers are only unmarshaled as `nil` when the relevant key/value pairs are left out of the JSON entirely. Fields with an explicit `null` are unmarshaled into a struct with an empty value for the struct's Value field.
=> unmarshal null wrapper types to nil instead of empty values

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This was missed in 748d386b5c1ea99658fd69fe9f03991ce86a90c1.
@cybrcodr another small issue following on from discussion in https://github.com/golang/protobuf/pull/338.
=> jsonpb: don't allocate memory for null-value reference types

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This is meant for use with dynamic message registries, where message descriptors could be downloaded from another source and still properly serialized/de-serializing from JSON, even when present in an `Any` message.
I've used an interface to represent the resolver instead of a function type because I have need for it to be backed by a non-function type (and just closing over variables isn't sufficient). The reason it needs to be an interface is for implementations of `JSONPBMarshaler` and `JSONPBUnmarshaler` that might want to decorate the resolver -- e.g. wrap it in a way that can supply additional message types. In such a case, we don't want to wrap the resolver more than once (which could happen since JSON serialization/de-serialization is recursive, and nested fields could also be …
=> support custom URL resolver when marshaling/unmarshaling Any messages to/from JSON

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Hi, our test cases are failed by #394 .  
We defined a struct which implements interface `JSONPBUnmarshaler`, and use it as a field in another message, for example:
```protobuf
message MyString {
bool null = 1;
string value = 2;
}
message Request {
MyString name = 1;
}
```
`MyString` implements `JSONPBUnmarshaler `.
Before #394 , everything works fine.  
After #394 , if input json is `{"name": null}`, func `UnmarshalJSONPB` on `MyString` is not executed. Because it will return earlier:
```go
if string(inputValue) == "null" && targetType != reflect.TypeOf(&stpb.Value{}) {
return nil   // <---returned here
}
```
=> Unmarshal a value which implements JSONPBUnmarshaler

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Add check for nil in Marshal and return error to avoid panic.
=> jsonpb: check for nil in Marshal and return error to avoid panic.

proto/extensions.go
The %v verb in Errorf automatically calls the String method.
This is safer than manually calling reflect.Type.String since
the reflect.Type may be nil.
=> Use fmt.Errorf instead of errors.New

protoc-gen-go/generator/generator.go
Change the pre-gofmt generated code for oneof discriminant interfaces
from:
type T interface { T() }
to:
type T interface {
T()
}
Prior to Go 1.9, gofmt rewrote the single-line form into the multi-line
one. Go 1.10 and later preserve the single-line form for single-method
interfaces. Generating code that is handled identically by both versions
of gofmt avoids spurious diffs with golden test data.
Change-Id: Ibb229827823a50e963bcd1b34e59a286654b415f
=> [dev] protoc-gen-go: format interfaces for gofmt 1.9 and 1.10

proto/extensions.go, proto/extensions_test.go
This is the same as #420, but for the `dev` branch. This would resolve #385.
=> expose accessor for value of unregistered extensions [dev]

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
The change does not handle negative values correctly.
This reverts commit 1e59b77b52bf8e4b449a57e6f79f21226d571845.
=> Revert "fix unnecessary rounding to float64 precision when JSON-marshaling durations (#453)"

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Fixes regression caused by #453.
@dsnet
=> jsonpb: fix handling of illegal and negative nanoseconds

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
This PR addresses the issue of:
#488
=> jsonpb: change Marshal to trim timestamp/duration to 0 fractional digits if possible

proto/discard.go, proto/discard_test.go
Not all proto.Message implementations will be updated to be
using the most recent protoc-gen-go. Thus, they will lack an
XXX_DiscardUnknown method. Add logic to handle older protobufs.
=> proto: add logic to handle legacy message

proto/discard.go
This copies the discardLegacy logic from the dev branch.
The unit tests are located on the dev branch and will be merged
into the master branch in the near future.
This function is cherrypicked into master in order to support the
master to dev transition.
=> proto: add DiscardUnknown function

proto/all_test.go, proto/lib.go, proto/table_marshal.go, proto/table_unmarshal.go
The proto2 and proto3 specifications explicitly say that strings must be
composed of valid UTF-8 characters. Thus, report a marshal/unmarshal error
if any string fields are invalid.
The C++ implementation prints an error anytime invalid UTF-8 strings
is present during parsing or serializing. For proto3, it explicitly
errors out when parsing an invalid string.
In Go, we'll attempt to apply this check on proto2 and proto3,
but may relax that constraint depending on the extent of problems.
=> proto: reject invalid UTF-8 in strings

_conformance/conformance.pb.go, _conformance/conformance_proto/conformance.pb.go, jsonpb/jsonpb_test_proto/more_test_objects.pb.go, proto/lib.go, proto/proto3_proto/proto3.pb.go, proto/proto3_test.go, proto/table_unmarshal.go, protoc-gen-go/generator/generator.go, ptypes/any/any.pb.go, ptypes/duration/duration.pb.go, ptypes/empty/empty.pb.go, ptypes/struct/struct.pb.go, ptypes/timestamp/timestamp.pb.go, ptypes/wrappers/wrappers.pb.go
This flag was necessary inside Google for the transition to having
proto3 preserve unknown fields by default.
Outside of Google, this is unnecessary since the dev branch is
the transition.
=> proto: remove Proto3UnknownFields flag

proto/extensions_test.go, proto/text_parser_test.go
For now, use fmt.Sprintf to get the proper type name that is
agnostic to the package that the type is defined in.
However, in the future, we should avoid such brittle testing
and have more distinguishable errors.
=> proto: robustify tests that compare error messages

proto/extensions_test.go
In Go 1.10, `go test` automatically runs `go vet` as well.  This
uncovered a vet failure in `TestUnmarshalRepeatingNonRepeatedExtension`
where `pb.ComplexExtension` is passed as a `fmt.Stringer` to `t.Errorf`.
The string method exists only on the pointer-receiver type,
`*pb.ComplexExtension`.
=> proto: fix govet failures in Go 1.10

proto/extensions_test.go, protoc-gen-go/generator/generator.go
In Go 1.10, go vet and gofmt have changed their output in a way to breaks the current build and test cycle.
* gofmt turns a one-line definition of a single-method interface into three lines; this causes a golden 
comparison test to produce different results between Go 1.9 and Go 1.10.
* go vet is now run by default with go test, which uncovered a bad Stringer argument in extension_test.go.
Tested on Go1.10rc1 and Go1.9.3.
=> proto,protoc-gen-go: fix vet and gofmt errors for Go 1.10

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
As mentioned in #509, `jsonpb` panics when marshaling/unmarshaling a non-generated message that has an unexported pointer field. This change will restore [dynamic messages](https://godoc.org/github.com/jhump/protoreflect/dynamic) to working with `jsonpb` (they work fine in `master`; just broken in this `dev` branch as of #472).
=> don't panic when trying to check for required fields

proto/all_test.go, proto/table_unmarshal.go
Previously, an error was returned during unmarshal when a wiretype
was encountered that did not match the expected wiretype.
In order to match the behavior of the C++ and Python implementations,
we no longer return an error and instead store the bad wire fragment
as an unknown field (or skip them if unknown field preservation is disabled).
The generator still produces code that references ErrInternalBadWireType
for the unmarshal logic for oneof fields.
However, the current proto package does not use the generated unmarshalers
for oneofs, so their existence has no bearing on unmarshal semantics.
Cleaning up the generator to stop producing these is future work.
=> proto: treat bad wire types as unknown fields

proto/pointer_reflect.go, proto/pointer_unsafe.go, proto/table_unmarshal.go
In the case of a tag of zero, we perform some pointer arithmetic
where we add -1 to the pointer. Even though we do not end up dereferencing
the pointer, this still causes issues with the Go GC, which expects that
every Go pointer is a valid pointer.
This causes crashes on Go1.7 and below because the function arguments
are considered live throughout the entire function causing the GC to
scan this invalid pointer. On Go1.8 and above, this is not an issue
since the argument is not considered live and is not scanned.
To be on the safer side, perform pointer arithmetic that is effectively
a noop, so that we don't cause a valid pointer to become invalid.
=> proto: avoid pointer arithmetic with invalidField

protoc-gen-go/testdata/main_test.go
No particular reason for this to be a ./ import, and it confuses vgo.
=> protoc-gen-go: remove relative import in main_test.go

_conformance/conformance.pb.go, jsonpb/jsonpb_test_proto/more_test_objects.pb.go, jsonpb/jsonpb_test_proto/test_objects.pb.go, proto/decode.go, proto/table_marshal.go, proto/test_proto/test.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/extension_base/extension_base.pb.go, protoc-gen-go/testdata/extension_extra/extension_extra.pb.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go, protoc-gen-go/testdata/imp/imp.pb.go, protoc-gen-go/testdata/imp/imp2.pb.go, protoc-gen-go/testdata/imp/imp3.pb.go, protoc-gen-go/testdata/multi/multi1.pb.go, protoc-gen-go/testdata/multi/multi2.pb.go, protoc-gen-go/testdata/multi/multi3.pb.go, protoc-gen-go/testdata/my_test/test.pb.go, protoc-gen-go/testdata/proto3/proto3.pb.go
As part of the recent protobuf optimization work, we started generating
Unmarshal and Marshal methods on generated messages. These were done to
support the table-driven implementation within the proto package.
We are renaming Marshal as XXX_Marshal and Unmarshal as XXX_Unmarshal
to make it clear that users are not supposed to call these directly.
There are several reasons for the rename:
* The Marshal method assumes that deterministic is the only option we
would ever support for protos, and is not very forward compatible.
* The presence of a deterministic boolean is confusing for users,
where many set it without considering whether it is necessary.
* The Unmarshal method has a slightly different semantic than the previously
documented proto.Unmarshaler interface. The documented Unmarshal …
=> Rename generated Marshal and Unmarshal protobuf method

protoc-gen-go/testdata/imports/fmt/m.pb.go, protoc-gen-go/testdata/imports/test_a_1/m1.pb.go, protoc-gen-go/testdata/imports/test_a_1/m2.pb.go, protoc-gen-go/testdata/imports/test_a_2/m3.pb.go, protoc-gen-go/testdata/imports/test_a_2/m4.pb.go, protoc-gen-go/testdata/imports/test_b_1/m1.pb.go, protoc-gen-go/testdata/imports/test_b_1/m2.pb.go, protoc-gen-go/testdata/imports/test_import_a1m1.pb.go, protoc-gen-go/testdata/imports/test_import_a1m2.pb.go, protoc-gen-go/testdata/imports/test_import_all.pb.go, protoc-gen-go/testdata/imports/test_import_public.pb.go
New tests weren't updated for renamed Marshal/Unmarshal methods.
=> protoc-gen-go: regenerate golden tests

README.md
We're only testing with 1.6+, so claiming support for earlier versions is dubious.
=> README: change minimum required Go version Go 1.6

_conformance/conformance.pb.go, jsonpb/jsonpb_test_proto/test_objects.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/imports/fmt/m.pb.go, protoc-gen-go/testdata/imports/test_import_a1m1.pb.go, protoc-gen-go/testdata/imports/test_import_a1m2.pb.go, protoc-gen-go/testdata/imports/test_import_all.pb.go, protoc-gen-go/testdata/imports/test_import_public.pb.go
Rework the handling of imported packages.
Do not add imported protobuf packages to a global registry. Instead,
maintain a per-file list of packages and names. This avoids imports
in one file affecting the generated code in a second one.
Consistently deal with imports in terms of import path, rather than
source file. This avoids imports of two .proto files in the same
Go package producing redundant import statements.
Introduce ImportPath and PackageName types to prevent confusion about
which values contain import paths ("github.com/golang/protobuf/proto")
and which contain package names ("proto").
Convert many uses of FileDescriptorProto to FileDescriptor, for
consistency and general convenience.
=> protoc-gen-go: handle package import names per-file

README.md, protoc-gen-go/generator/generator.go, protoc-gen-go/golden_test.go
When --go_out=paths=source_relative:., output filenames are always
derived from the input filenames. For example, the output file
for a/b/c.proto will always be a/b/c.pb.go, regardless of the
presence or absence of a go_package option in the input file.
Fixes #515.
=> protoc-gen-go: add paths=source_relative option

protoc-gen-go/generator/name_test.go
Broken by addition of GoImportPath/GoPackageName.
=> protoc-gen-go: fix test

.travis.yml, README.md, protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go
This change effectively makes Go1.9 the minimum required version of Go
when using gRPC since type aliases are needed to truly unify context.
Even though this only affects those who use gRPC, there are other reasons we
need Go1.9 (such as type aliases for import public).
Fixes #537
=> protoc-gen-go: use standard library context (requires Go1.9)

protoc-gen-go/golden_test.go
On windows, the wantFiles in TestParameters will never match the
files discovered when doing filepath.Walk, because of the difference
in filepath separators.  For windows, just use filepath.To/FromSlash
to convert before comparing to the set of test cases.
=> golden_test: normalize path separators for Windows

protoc-gen-go/generator/generator.go, protoc-gen-go/golden_test.go
Fix a bug which caused us to generate a blank import comment when go_package
contains just a package name (no import path):
package foo // import ""
Fixes #553
=> protoc-gen-go: don't generate blank // import comment

jsonpb/jsonpb_test_proto/test_objects.pb.go, proto/test_proto/test.pb.go, protoc-gen-go/descriptor/descriptor.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/extension_base/extension_base.pb.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go, protoc-gen-go/testdata/imp/imp.pb.go, protoc-gen-go/testdata/my_test/test.pb.go
The ExtensionRange struct isn't going to change, but do so silences go vet.
Fixes #214
=> protoc-gen-go: use keyed ExtensionRange literals

protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go
The generator includes a hack for generating the name of fields which
extend proto2.bridge.MessageSet. (The ultimate motivation appears to
be compatibility with proto1 text formats.) Apply this hack based
on whether the message being extended defines the message_set_wire_format
option, not on the local name of that message type.
=> protoc-gen-go: Don't rely on local package name for mset name hack.

ptypes/any/any.pb.go, ptypes/any/any.proto
An extra space was causing Examples 3 and 4 to render in Example 2's code block. This commit fixes those minor typos.
Also removing the `====` denoting the JSON section will allow godoc to render a heading here.
<details><summary>Before - click to expand</summary><p>
</p></details>
<details><summary>After - click to expand</summary><p>
</p></details>
=> Fix minor godoc typos in any package

proto/all_test.go, proto/table_unmarshal.go
A prior changed (see #511) allows Unmarshal to treat fields with
unknown wire types with known tags as unknown fields.
When doing so, we must be careful not to set the required field bit.
For example, suppose we have:
message Foo { require fixed32 my_field = 1; }
Then parsing a message with a field of type varint and tag 1 should
not satisfy the required that Foo.my_field be set.
=> proto: do not allow unknown fields to satisfy required field bit

protoc-gen-go/generator/generator.go, protoc-gen-go/golden_test.go
An earlier change inadvertendly made the import_path flag stop setting
the package name. In addition, we intentionally removed the behavior where
a go_package option in one file would set the package name for other
generated files, in anticipation of allowing a single compilation action
to generate code for many packages.
This change restores the import_path behavior. It also permits a go_package
option in one file to affect other files *in the same package*. (Every
source file should include a go_package option, which makes this case moot,
but this minimizes the amount of breaking change that we're introducing.)
Also tweak assignment of import paths to allow the import_path flag to
set the import path for all generated files.
=> protoc-gen-go: fix up generation of package names

README.md, protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go
This reverts commit 3dc8a89f965ba7bf716fd0d92b83c5da1792ab9c.
cc #537, #579
=> Revert "protoc-gen-go: use standard library context (requires Go1.9) (#548)"

protoc-gen-go/golden_test.go
The 1.9 release tag is "go1.9", not "1.9".
=> protoc-gen-go: fix release tag in golden_test

ptypes/any.go, ptypes/any_test.go
Microbenchmark, running ptypes.Is in a tight loop, shows the execution time drops by 50%.
The exact results depend on any TypeUrl, message type, and CPU architecture.
While at it, test corner cases for Empty, which indirectly tests AnyMessageType corner cases.
=> ptypes: optimize Is to avoid prefix scan

protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go
Corresponding grpc PR: https://github.com/grpc/grpc-go/pull/2060
=> grpc: document ctx closure best practices

proto/encode.go
The new table-drive unmarshaler never emits "{Unknown}",
so that comment is stale.
Also, there is no reason to document that the name of "first" missing
required field is stored:
* There is no programmatic way to access this field, so it is just for user debugging.
* "First" is not well defined. First encounted while parsing? First listed in proto file? First listed in the Go struct?
=> proto: adjust documentation on RequiredNotSetError

LICENSE, README.md
The first line of the LICENSE was a package title, which confuses
license checkers such as that run by GitHub. Move the title to
README.md, where it belongs.
=> LICENSE: Move title to README.md

protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go
32a84b2 added a newline that resulted in the interface doc comment
becoming detached from the interface type definition. However, both it
and the corresponding server comment were inconsistent, so this change
makes them all consistent and well-rendered in godoc.
=> grpc: fix and improve interface comments for client/server types

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Fix unmarshaling JSON object with escaped string into Struct type.
Fixes #605
=> jsonpb: fix unmarshaling JSON object with escaped string into Struct type

proto/table_marshal.go, proto/table_unmarshal.go
Instead of simply saying there was a UTF-8 validation error, specify
which field in which message had an issue.
=> proto: mention field name in error message

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Ran into an issue where attempting to unmarshal valid json that contains a field with a single enum into a message that has a repeated enum field causes a panic. For example, try to unmarshal this:
```go
{
"rFunny":"PUNS"
}
```
into a message that looks like this:
```go
type Message struct {
RFunny []Message_Humour
}
```
This will cause a panic. I know the json is an invalid representation of the Message struct, but it shouldn't panic. I'm attempting to fix this issue by validating that the targetType is correct before setting the enum.
=> jsonpb: error on scalar enum provided for repeated enums instead of panic

ptypes/any_test.go
Just ran
gofmt -w .
on the project root. That's all.
https://blog.golang.org/go-fmt-your-code
---
> I made this PR with a project going on over at https://github.com/rotblauer/gofmt-att, and it's definitely a work in progress. So if I got something wrong, or this is annoying at all, please file an issue over there and we'll sort it out.
=> ptypes: ran gofmt on any_test.go

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go, proto/properties.go, proto/text.go, proto/text_parser.go
Export `mtype`, `mkeyprop`, `mvalprop` fields from `proto.Properties` for usage outside `proto` package.
Fix up `jsonpb` pending TODOs.
Fixes #644
=> jsonpb: handle map keys' and values' properties properly

proto/all_test.go, proto/table_marshal.go
PR #650 added strict checking of the use of deterministic with custom marshalers
since it is impossible to know whether a custom marshalers actually do produce
deterministic output or not.
However, this check is breaking hundreds of targets that already rely on
determinism along with custom marshalers. In every case, the custom marshaler
already produced deterministic output, so it did not really matter.
If deterministic is specified *and* a custom marshaler is not actually
deterministic, then the output is obviously not deterministic,
and setting the flag was a lie. However, there is not much we can do with the
current API. A redesign of the proto API will resolve this tension.
=> proto: revert strict erroring of deterministic and custom marshalers

jsonpb/jsonpb.go
Strictly document that custom JSONPBMarshaler and JSONPBUnmarshaler must
properly follow the JSON to proto specification:
https://developers.google.com/protocol-buffers/docs/proto3#json
These interfaces are currently necessary since there is no high-level API
for proto reflection. However, as we prepare to move to a world where there is
first-class support for proto reflection, these interfaces should be deprecated.
When we eventually have proto reflection, and implement jsonpb entirely
in terms of reflection, then it should not matter whether we called these
custom marshalers or not since they should both implement the same specification.
Note that this documentation is already implied by the fact that this whole
package implements the proto-JSON specification and in order for it to do …
=> jsonpb: strictly document JSONPBMarshaler and JSONPBUnmarshaler behavior

proto/all_test.go, proto/encode.go, proto/lib.go, proto/table_marshal.go, proto/table_unmarshal.go
The current logic currently treats RequredNotSetError as a non-fatal
error such that it continues to proceed with its normal execution, but
returns that non-fatal error at the end.
We now make it such that invalid UTF-8 is also a distinguishable error
that is treated as non-fatal by the execution logic. In the rare event
that both an RequiredNotSet error and InvalidUTF8 error is encountered,
the first one encountered is returned.
In the process of making this change, we also fix a number of cases where
RequiredNotSet was treated as fatal, when it should not have been non-fatal
(notably in the logic for extensions, message sets, and maps).
This change deliberately does not provide an API make it easy to distinguish
invalid UTF-8 errors as this is not a normal behavior we want users to …
=> proto: make invalid UTF-8 errors non-fatal

Makefile, jsonpb/jsonpb_test.go
The purego implementation is unable to handle unexported fields since it is
impossible for purego code to mutate such fields without using unsafe.
Also, modify the Makefile to test the purego code paths.
Fixes #670
=> jsonpb: avoid unexported fields in hand-crafted message

README.md
=> README.md, proto: Replaced usage of group in example 

proto/all_test.go, proto/table_marshal.go, proto/table_unmarshal.go
The previous logic only treated a required not set violation as non-fatal
for the first instance. Afterwards, the logic incorrectly switched back
to being fatal.
=> proto: fix handling of required fields after multiple violations

proto/extensions.go
Including the types that are mismatched, rather than just stating that there was a type mismatch makes the error easier to debug and fix.
=> More useful error message on setting extensions

conformance/internal/conformance_proto/conformance.pb.go, jsonpb/jsonpb_test_proto/more_test_objects.pb.go, jsonpb/jsonpb_test_proto/test_objects.pb.go, proto/proto3_proto/proto3.pb.go, proto/test_proto/test.pb.go, protoc-gen-go/descriptor/descriptor.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/import_public/sub/a.pb.go, protoc-gen-go/testdata/imports/test_a_1/m1.pb.go, protoc-gen-go/testdata/multi/multi2.pb.go, protoc-gen-go/testdata/multi/multi3.pb.go, protoc-gen-go/testdata/my_test/test.pb.go, protoc-gen-go/testdata/proto3/proto3.pb.go, ptypes/struct/struct.pb.go
Trivial change, but eliminates a source of minor diffs between the
current protoc-gen-go and the protogen-backed one.
=> protoc-gen-go: add blank lines between various enum functions

go.mod, go.sum
Go 1.11 is now released with preliminary support for Go modules.
If a repository is checked outside of the GOPATH, then the Go toolchain will
use the module support by default. However, it requires a go.mod file so that
the toolchain can derive the import paths of all packages living under the
tree containing the go.mod file.
=> go.mod: add module file

proto/table_unmarshal.go
len never returns negative values, so len(b)==0 states
requirements in a more clear way with less "uncertainty".
=> proto: replace len(b)<=0 with len(b)==0

proto/size2_test.go, proto/table_marshal.go
Use named constants from math package instead of expressions
that evaluate to the same value.
=> proto: replace exprs with matching consts from math pkg

proto/decode.go
The "return 0, errOverflow" already tells that x is always zero.
If there is a mistake, this code path should be fixed,
otherwise code that is disabled does not add any value.
=> proto: remove commented-out code

jsonpb/jsonpb_test_proto/test_objects.pb.go, proto/test_proto/test.pb.go, protoc-gen-go/descriptor/descriptor.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/extension_base/extension_base.pb.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go, protoc-gen-go/testdata/my_test/test.pb.go
Add a blank line between the ExtensionRangeArray and XXX_Unmarshal methods.
=> protoc-gen-go: add blank line after extension method

jsonpb/jsonpb_test_proto/test_objects.pb.go, proto/test_proto/test.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go
This tag is not used by jsonpb. Future releases of protoc will stop
including a json_name field in extension descriptors.
=> protoc-gen-go: don't set the json tag on extension fields

protoc-gen-go/generator/generator.go, protoc-gen-go/generator/name_test.go
Don't generate identifiers that conflict with predeclared identifiers, prepend with "_" instead. This matches the behavior for package names that are Go keywords.
We ran into this issue during https://github.com/envoyproxy/envoy/pull/4556. Code with import statement:
```
import string "github.com/envoyproxy/data-plane-api/api/string"
```
was being generated and would not compile.
The list of predeclared indentifiers was taken from: https://golang.org/ref/spec#Predeclared_identifiers
=> protoc-gen-go: predeclared identifiers in cleanPackageName

protoc-gen-go/generator/generator.go, protoc-gen-go/generator/name_test.go
Permit creating a generated package named e.g., "string". Apply disambiguation
to prevent creating a local import name that conflicts with predefined
identifiers; importing package "string" will be done as:
import string1 "string"
=> protoc-gen-go: only disambiguate predefined idents for local package names

proto/deprecated.go, proto/message_set.go, proto/message_set_test.go, proto/table_unmarshal.go, proto/test_proto/test.pb.go, protoc-gen-go/generator/generator.go, protoc-gen-go/testdata/extension_base/extension_base.pb.go, protoc-gen-go/testdata/extension_user/extension_user.pb.go, protoc-gen-go/testdata/my_test/test.pb.go
Despite the naming, these are "internal-only" functions that are intended to
only be called from generated code for MessageSets.
Furthermore, MessageSets are themselves a deprecated feature from proto1 days,
such that descriptor.proto even warns against their use since the initial
open-source release of protocol buffers in 2008. Within Google,
there are no direct usages of these functions, and all existing
usages of MessageSets go through the new table-driven implementation.
In addition to deprecating the {Unm,M}arshalMessageSet{JSON} top-level functions,
also modify the generator to stop emitting MarshalJSON and UnmarshalJSON methods
for messages sets. The UnmarshalJSON method is not implemented and the
MarshalJSON method does not seem to be called anywhere in Google (verified by
making …
=> proto: deprecate {Unm,M}arshalMessageSet{JSON}

proto/clone_test.go, proto/equal.go, proto/extensions.go, proto/pointer_reflect.go, proto/pointer_unsafe.go, proto/table_marshal.go
The current API represents scalar extension fields as *T and
repeated extension fields as []T.
However, this is not an accurate reflection of the protobuf data model.
For scalars, pointers are usually used to represent nullability. However,
in the case of extension scalars, there is no need to do so since presence
information is captured by checking whether the field is in the extension map.
For this reason, presence on extension scalars is not determined by checking
whether the returned pointer is nil, but whether HasExtension reports true.
For repeated fields, using []T means that the returned value is only a partially
mutable value. You can swap out elements, but you cannot change the length of
the original field value. On the other hand, the reflective API provides methods
on repeated …
=> proto: store extension values according to protobuf data model

README.md
If your code is locked to a specific version of `github.com/golang/protobuf` (e.g., 1.2.0), the default suggestion of `go get -u github.com/golang/protobuf/protoc-gen-go` may end up building and installing an incompatible version of `protoc-gen-go` (e.g., as introduced by https://github.com/golang/protobuf/blame/8d0c54c1/proto/proto3_proto/proto3.pb.go#L23).
Provides a workaround for #738.
=> README.md: document how to build a specific version of `protoc-gen-go`

ptypes/duration.go
It is spec'd that way, but best practice is to avoid it.
=> Avoid assuming time.Duration is nanoseconds

ptypes/timestamp.go
The existing code is much more complex.
=> More cleanly construct a Timestamp

go.mod, go.sum, proto/extensions_test.go
Removes two go mod dependencies on `golang.org/x/sync` and indirectly on `golang.org/x/net`. These were being used to provide an `errgroup.Group` to collate errors in a test.
This PR provides the same functionality but using `sync.WaitGroup`.
=> proto: remove test dependency on experimental packages

protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go, protoc-gen-go/testdata/grpc/grpc.pb.go
Avoid using an errUnimplemented function, which requires us to
give a name to it, causing possible conflicts.
Instead, just inline it's functionality.
Fixes #817
=> protoc-gen-go/grpc: inline errUnimplemented function

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
If an Any message contains a message that knows how to marshal itself (e.g implements the `JSONPBMarshaler` interface), the resulting JSON is not correctly indented. This is due to the place where the JSON is re-written to add the `@type` attribute not correctly respecting the `Indent` field.
=> fix indentation in jsonpb with Any messages

proto/properties.go
Re-opening #829 per conversation with @neild https://github.com/golang/protobuf/pull/829#issuecomment-492840829
Convert prints to `os.Stderr` to Go's `log.Printf` to remain consistent with the rest of the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/golang/protobuf/851)
=> Log parsing errors using log pkg

jsonpb/jsonpb.go, jsonpb/jsonpb_test.go
Fix output for negative nanoseconds with zero second.
Add validation on min/max seconds.
Fixes #883
=> jsonpb: fix marshaling of Duration

go.mod, jsonpb/jsonpb.go, proto/all_test.go, proto/text.go
The reflect.Value.Interface method shallow copies the underlying value,
which may copy mutexes and atomically-accessed fields.
Some usages of the Interface method is only to check if the interface value
implements an interface. In which case the shallow copy was unnecessary.
Change those usages to use the reflect.Value.Implements method instead.
Fixes #838
=> all: fix reflect.Value.Interface races

protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/deprecated/deprecated.pb.go
The deprecated comment was only added to the method of an unexported type.
https://github.com/grpc/grpc-go/issues/3023
=> protoc-gen-go: fix deprecated comment for grpc methods

jsonpb/jsonpb_test.go, proto/all_test.go, proto/encode_test.go, proto/extensions_test.go, proto/lib.go, proto/map_test.go, protoc-gen-go/generator/generator.go, protoc-gen-go/generator/internal/remap/remap.go, protoc-gen-go/grpc/grpc.go, protoc-gen-go/testdata/import_public_test.go
Golang code usually used `marshal` instead of `marshall`.
=> Fix typos in comments, tests and function names

go.mod, go.sum, internal/cmd/generate-alias/main.go
In https://golang.org/cl/219598, we removed patching the well-known types
with an explicit go_package option and instead relied on M flags.
The lack of updated go_package options broke generate-alias since it
appears as if the import public is trying to alias Go identifiers
within the same Go package (thus generating nothing).
We fix generate-alias by replicating the same approach here,
where we construct the M flag mapping and pass it to protoc-gen-go.
=> internal/cmd/generate-alias: fix generator for lacking go_package options

proto/registry.go
Fixes #1092 "registry: FileDescriptor should mention protoregistry.GlobalFiles.FindFileByPath as replacement"
=> proto: fix stale deprecation documentation on registry functions

protoc-gen-go/grpc/grpc.go
Even through the grpc package is excluded from our compatibility agreement,
the v1.4.0 release accidentally reverted the package to an older revision.
Update this code to be identical to the v1.3.5 release (barring non-semantic
documentation changes).
Fixes #1111
=> protoc-gen-go/grpc: make grpc identical to v1.3.5

jsonpb/decode.go
Because `in` is a []byte, as written this prints a list of integers instead of the unrecognized enum value.
=> jsonpb: fix a confusing error message

proto/deprecated.go
The InternalMessageInfo type only exists to implement the
XXX methods on generated messages where those methods were
only ever intended to be called by this module itself.
Since v1.4.0, this module no longer relies on the XXX methods,
so the InternalMessageInfo and its implementation is supposed
to be dead code. Unfortunately, there are external usages that
violate our compatibility agreement and either directly call
the XXX methods or indirectly call it because some library
type-asserts to the existence of these methods.
This change adds minimal support for InternalMessageInfo by
just calling out directly to the v2 implementation.
=> proto: make InternalMessageInfo functional

proto/text_decode.go
Go 1.15 introduced a new `go vet` warning (https://golang.org/doc/go1.15#vet) for conversions of the form `string(x)` where `x` is an integer type other than `rune` or `byte`. This warning is enabled by default when running `go test`. As a consequence, running `go test github.com/golang/protobuf/proto` results in a build failure prior to this commit.
Fixes #1209.
=> proto: convert integer to rune before converting to string

descriptor/descriptor.go, proto/registry.go
Use protodesc.ToFileDescriptorProto to retrieve the raw descriptors
for legacy support instead of the undocumented ProtoLegacyRawDesc method
that we expect the newer module to provide.
This change will cause the legacy proto package to incur a dependency
on the descriptorpb package.
=> all: rely on protodesc.ToFileDescriptorProto

jsonpb/decode.go, jsonpb/json_test.go
Change how jsonpb.Unmarshal handles nested JSONPBMarshaler fields a null json values.
When json null is encountered for a field which implements JSONPBUnmarshaler, jsonpb will now calli unmarshal method from the field, instead of just assigning nil to this field.
=> jsonpb: bring back old behaviour of handling nulls and JSONPBUnmarshaler

go.mod
Use the new deprecation feature to mark this module as deprecated.
See https://golang.org/issue/40357.
Considerations:
* google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0 and below
used to generate a hard dependency on github.com/golang/protobuf,
which would be frustrating since it would force an explicit dependency
on a deprecated module. However, that is no longer the case in v1.26.0.
* google.golang.org/protobuf and github.com/golang/protobuf have
a cyclic dependency on each other. However, this should not be a problem
since proposal 40357 only marks direct dependencies in the go.mod file,
rather than all transitive dependencies in the go.sum file.
=> all: deprecate the module
